version: '3'
services:
  gatling-runner:
    build: .
    command: -r ${AWS_REPORT_BUCKET}
    environment:
      - GATLING_NR_USERS=${GATLING_NR_USERS}
      - GATLING_MAX_DURATION=${GATLING_MAX_DURATION}
      - GATLING_RAMPUP_TIME=${GATLING_RAMPUP_TIME}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
