name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install required dependencies
        run: |
          pip install --user awscli
          npm install -g aws-cdk

      - name: Build gatling-runner
        working-directory: ./gatling-runner
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean package

      - name: Setup infra
        env:
          AWS_DEFAULT_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VPC_ID: "vpc-bf6957d9"
          S3_BUCKET_NAME: "gatling-runner"
        working-directory: ./gatling-infra
        run: |
          mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean package
          cdk deploy GatlingRunnerEcsStack --require-approval never
